### PR TITLE
Feature/hpccm

### PR DESCRIPTION
**Pull request by mmiesch**
This PR does two things.

First, it make use of nvidia's hpc container maker (hpccm) to automatically generate the Dockerfile.  The main advantage of this is that it makes it much easier to configure the mpi installation for hpc systems.  For example, this PR includes support for Mellanox infiniband OFED drivers and intel's performance scaled messaging (PSM) library, which I know Cheyenne uses.  An added bonus of hppcm is that it makes it very easy to install selected versions of the gnu compilers and cmake.

The second thing this PR does is to adapt docker_base for use with the new jedi-stack build system.  So, the installation of nceplibs and tkdiff have been moved to jedi-stack.

This PR will soon be followed by associated PRs in the docker, jedi-stack and charliecloud repos.

### CODE REVIEW

**Comment by markjolah** [comment]
Tried to get started on the review, but my version of hpccm I just installed seems to build a different Dockerfile than what is checked in.

I used pip to install hpccm-19.5.1

I am attaching the diff between Dockerfile's.  I am guessing you used an older version to generate the file.  Probably we need to settle on a fixed version of hpccm?
[Dockerfile.diff.txt](https://github.com/JCSDA/docker_base/files/3303850/Dockerfile.diff.txt)

**Comment by mmiesch** [comment]
Thanks @markjolah for noticing this - I switched to that version of hpccm and put it in the docs.  Please compare again

**Comment by markjolah** [comment]
After testing, both old and new versions of the hpccm Dockerfile seem to work.  I tested using the generated images as the `FROM` images for the main docker branch feature/jedi-stack, then I was able to build and pass all tests on ufo-bundle.  I can also test fv3-bundle if that would be useful.

One thought:  It seems like it would be nice to have some permanent indication of exactly which hpccm version was used to generate the Dockerfile.  Maybe a little helper script could do it.  Something like
```
#!/bin/bash

HPCCM=hpccm

$HPCCM --recipe base.py --format docker > Dockerfile
echo "Generated with hpccm version: " > generated.version
$HPCCM --version >> generated.version
```

**Comment by mmiesch** [comment]
@markjolah - good idea!  I added your script.

**Comment by markjolah** [comment]
One last request: can we add the programs "nano" and "screen" to the base image.  They take up almost no space and would make it easier for me to work with the images.

**Review by xinzhang8noaa — APPROVED** [review]

**Comment by markjolah** [comment]
Unfortunately one more issue.  I did try the fv3-bundle and I'm getting many MPI? related error messages with any container building from the hpccm base.
Running for instance: 
```
ctest -VV -R test_fv3jedi_hyb4dvar_geos
```
I get many hundreds of lines like this, even though the test does pass
```
343: [e18413f6edfd:25847] Read -1, expected 20736, errno = 1
```
These errors are not present on amazon jedi-stack-v3 AMI images.

Incidently, the test `test_fv3jedi_hyb4dvar_gfs` is failing in both old and new docker images and on jedi-stack AMI images.  I can get it to pass on my laptop.  The success/failure of this test doesn't seem to directly correlate to the use of hpccm base, but when running in the hpccm environment I get the same sorts of MPI read error messages.

**Review by markjolah — APPROVED** [review]
Mark M. and I determined the MPI read errors I am seeing are not present in singularity or charliecloud versions of the container, but somehow just a Docker problem.  Since they don't apparently affect the success or failure of tests, and this PR is blocking many other essential PRs I will open a separate issue for the read failures.

**Pull request merged**
